from decouple import config as _config

LOGGING_DIR=_config("LOGGING_DIR")
LOGGING_FILE=_config("LOGGING_FILE")
LOGGING_WHEN=_config("LOGGING_WHEN")
LOGGING_INTERVAL=_config("LOGGING_INTERVAL")
LOGGING_TITLE=_config("LOGGING_TITLE")
LOGGING_LEVEL=_config("LOGGING_LEVEL")
LOGGING_HANDLERS=_config("LOGGING_HANDLERS", "")
LOGGING_FORMATTER=_config("LOGGING_FORMATTER", "")